### ISSUE TITLE
Markdown-parsed unordered list items include a line break after bullet point in Firefox

### ISSUE THREAD

**Issue by ty2k** [twinlabs/forum#170] opened 2015-08-04 00:21 UTC
When using Markdown to create an unordered list (starting a line with "- "), the forum wraps a list item in a paragraph tag. This renders the paragraph right after the bullet point in Chrome, but in Firefox desktop for Windows and mobile for Android, it creates a line break after the bullet point. Example:

Input:
![unordered-list-bug-firefox-input](https://cloud.githubusercontent.com/assets/10005102/9050452/f15141f0-3a0a-11e5-9e93-200fff76bfd0.png)

Firefox desktop for Windows output:
![unordered-list-bug-firefox](https://cloud.githubusercontent.com/assets/10005102/9050415/9fac5fba-3a0a-11e5-9403-7a19d1ebbf5b.png)

Chrome desktop for Windows output:
![unordered-list-bug-chrome](https://cloud.githubusercontent.com/assets/10005102/9050495/653a071e-3a0b-11e5-8a87-44f4e4dfe021.png)

Same results for Android versions of the browsers.

I assume the paragraph tag is because of our changes to Markdown behavior to get paragraphs spaced nicely?

Unordered lists written out in HTML and ordered lists made with Markdown or in HTML are not subject to this same line break and work as expected.

**Comment by nchase** [comment] 2015-12-30 23:41
> I assume the paragraph tag is because of our changes to Markdown behavior to get paragraphs spaced nicely?

there was no change to how we handle markdown for the spacing, that was all CSS.

peculiar bug though. is this still happening under the conditions that you mentioned? if we can reproduce it we need to pin down where it's happening. strongly doubt that forum code did this. it's either in the library (github.com/chjj/marked) or it's a browser bug.

**Comment by nchase** [comment] 2015-12-30 23:43
closing because I cannot reproduce in Firefox. please re-open if this is still an issue.

**Closed by nchase** 2015-12-30 23:43 UTC
